apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 20-nmstate-configuration-worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKc2V0IC1ldXgKCiMgQ2xlYW4gdXAgb2xkIGNvbmZpZyBvbiBiZWhhbGYgb2YgbXR1LW1pZ3JhdGlvbgppZiAhIHN5c3RlbWN0bCAtcSBpcy1lbmFibGVkIG10dS1taWdyYXRpb247IHRoZW4KICBlY2hvICJDbGVhbmluZyB1cCBsZWZ0IG92ZXIgbXR1IG1pZ3JhdGlvbiBjb25maWd1cmF0aW9uIgogIHJtIC1yZiAvZXRjL2Nuby9tdHUtbWlncmF0aW9uCmZpCgppZiBbIC1lIC9ldGMvbm1zdGF0ZS9vcGVuc2hpZnQvYXBwbGllZCBdOyB0aGVuCiAgZWNobyAiQ29uZmlndXJhdGlvbiBhbHJlYWR5IGFwcGxpZWQsIGV4aXRpbmciCiAgZXhpdCAwCmZpCgpzcmNfcGF0aD0iL2V0Yy9ubXN0YXRlL29wZW5zaGlmdCIKZHN0X3BhdGg9Ii9ldGMvbm1zdGF0ZSIKaG9zdG5hbWU9JChob3N0bmFtZSAtcykKaG9zdF9maWxlPSIke2hvc3RuYW1lfS55bWwiCmNsdXN0ZXJfZmlsZT0iY2x1c3Rlci55bWwiCmNvbmZpZ19maWxlPSIiCmlmIFsgLXMgIiRzcmNfcGF0aC8kaG9zdF9maWxlIiBdOyB0aGVuCiAgY29uZmlnX2ZpbGU9JGhvc3RfZmlsZQplbGlmIFsgLXMgIiRzcmNfcGF0aC8kY2x1c3Rlcl9maWxlIiBdOyB0aGVuCiAgY29uZmlnX2ZpbGU9JGNsdXN0ZXJfZmlsZQplbHNlCiAgZWNobyAiTm8gY29uZmlndXJhdGlvbiBmb3VuZCBhdCAkc3JjX3BhdGgvJGhvc3RfZmlsZSBvciAkc3JjX3BhdGgvJGNsdXN0ZXJfZmlsZSIKICBleGl0IDAKZmkKCmlmIFsgLWUgIiRkc3RfcGF0aC8kY29uZmlnX2ZpbGUiIF07IHRoZW4KICBlY2hvICJFUlJPUjogRmlsZSAkZHN0X3BhdGgvJGNvbmZpZ19maWxlIGV4aXN0cy4gUmVmdXNpbmcgdG8gb3ZlcndyaXRlLiIKICBleGl0IDEKZmkKCiMgSGFuZGxlIHRoZSBjYXNlIHdoZXJlIHdlJ3JlIG1pZ3JhdGluZyBmcm9tIGNvbmZpZ3VyZS1vdnMKb3ZzLXZzY3RsIC0tdGltZW91dD0zMCAtLWlmLWV4aXN0cyBkZWwtYnIgYnItZXgKCiMgSGFuZGxlIHRoZSBjYXNlIHdoZXJlIHdlJ3JlIG1pZ3JhdGluZyBmcm9tIE9wZW5TaGlmdCBTRE4Kb3ZzLXZzY3RsIC0tdGltZW91dD0zMCAtLWlmLWV4aXN0cyBkZWwtYnIgYnIwCgpjcCAiJHNyY19wYXRoLyRjb25maWdfZmlsZSIgL2V0Yy9ubXN0YXRlCnRvdWNoIC9ldGMvbm1zdGF0ZS9vcGVuc2hpZnQvYXBwbGllZAoK
        mode: 493
        path: "/usr/local/bin/nmstate-configuration.sh"

