---
- hosts: all
  become: yes
  strategy: free
  # speedup
  gather_facts: no
  tasks:
    - name: Write disable init interfaces file
      copy:
        dest: /etc/NetworkManager/system-connections/disable-init-interfaces
        content: |
          # primary
          # secondary
        owner: root
        group: root
        mode: '0644'
